name: rotating-cylinders-model-validation
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - rdflib
  - pip
  - pip:
      - "git+https://github.com/Simulation-Benchmarks/semantic-benchmark@14-changing-the-benchmark-zip-archive-structure"
      - "git+https://github.com/izus-fokus/snakemake-report-plugin-metadata4ing@v2.0.2#egg=snakemake-report-plugin-metadata4ing"
