version = 1

[[annotations]]
path = "README.md"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "docs/**"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "**/*.py"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**/Snakefile*"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "common/nextflow.config"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".github/workflows/*"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "REUSE.toml"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CITATION.cff"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "codemeta.json"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CHANGELOG.md"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.json"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.yml"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "requirements.txt"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.toml"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.ipynb"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/*.zip"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "benchmark/**"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "postBuild"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".pre-commit-config.yaml"
precedence = "closest"
SPDX-FileCopyrightText = "2026 The rotating-cylinders authors"
SPDX-License-Identifier = "CC0-1.0"
