name: provenance
# Environment for uploading provenance RO-Crates to RoHub.

channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.10
  - pip
  - pip:
      - git+https://github.com/Simulation-Benchmarks/semantic-benchmark@14-changing-the-benchmark-zip-archive-structure
