name: provenance
# Environment for uploading provenance RO-Crates to RoHub.

channels:
  - conda-forge

channel_priority: strict

dependencies:
  - python=3.10
  - pip
  - pip:
      - semantic-benchmark @ git+https://github.com/Simulation-Benchmarks/semantic-benchmark.git@22-adding-tool-name-and-software-version-to-final-rocrate
