name: RoHub Integration CI

on:
  schedule:
    - cron: '0 18 * * 5'

  workflow_dispatch:
    inputs:
      branch:
        description: Branch to run and publish
        required: true
        default: main
      use_production_rohub:
        description: Upload to production RoHub
        required: true
        type: boolean
        default: true
      dumux_software_version:
        description: DuMux version used for this run
        required: true
        type: string
        default: '3.1'
      openfoam_software_version:
        description: OpenFOAM version used for this run
        required: true
        type: string
        default: '2412'

permissions:
  contents: read

jobs:
  run-dumux:
    uses: ./.github/workflows/run-benchmark-dumux.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      software_version: ${{ inputs.dumux_software_version || '3.1' }}

  run-openfoam:
    uses: ./.github/workflows/run-benchmark-openfoam.yml
    with:
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      benchmark_file: benchmark/1.0.0/minimal-configurations.json
      software_version: ${{ inputs.openfoam_software_version || '2412' }}

  upload:
    needs: [run-dumux, run-openfoam]
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: dumux
            display_name: DuMux
            software_url: https://zbmath.org/software/14293
            software_version: ${{ inputs.dumux_software_version || '3.1' }}
          - tool: openfoam
            display_name: OpenFOAM
            software_url: https://zbmath.org/software/4317
            software_version: ${{ inputs.openfoam_software_version || '2412' }}
    uses: ./.github/workflows/upload-rocrate.yml
    with:
      tool: ${{ matrix.tool }}
      display_name: ${{ matrix.display_name }}
      software_url: ${{ matrix.software_url }}
      software_version: ${{ matrix.software_version }}
      checkout_ref: ${{ inputs.branch || github.ref_name }}
      use_production_rohub: ${{ inputs.use_production_rohub }}
    secrets: inherit
