name: OpenFOAM-CI
on:
  push:

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

jobs:
  openfoam-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-version: latest
            activate-environment: model-validation
            use-mamba: true

      - name: Set strict channel priority
        run: conda config --set channel_priority strict
        
      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.4.5

      - name: Update environment
        run: mamba env update -n model-validation -f $GITHUB_WORKSPACE/openfoam/environment_benchmarks.yml

      - name: Simulate rotating cylinders using OpenFOAM
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/openfoam
          python3 run_benchmark.py

      - name: Upload OpenFOAM results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: $GITHUB_WORKSPACE/openfoam/results
          retention-days: 5
